version: "3.7"
services:
  joomladb:
    image: mysql:5.7
#    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456qwe
    volumes:
      - db_data:/var/lib/mysql
  php:
#    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - joomladb
    ports:
      - 8081:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: 123456qwe
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
      # Define Joomla version and expected SHA512 signature
      JOOMLA_VERSION: 3.9.8
      JOOMLA_SHA512: 099ccb3b2d6cfb0b6d465f5f45a694e76744aff1a9e9ebf69b8697236849fd6568a6b0de593008ec60dbdb08547a7eee3da2a6c6315ae4013e32d02225a5ed66
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
volumes:
  db_data: {}

